#开发环境
spring:
  #    配置数据库连接
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  #    设置自动建表与显示SQL语句
  jpa:
    hibernate:
      ddl-auto: update #每次运行程序，没有表格会新建表格，表内有数据不会清空，只会更新
    show-sql: true

#    设置日志级别
logging:
  level:
    root: info
    cn.zh.blog: debug
  file: log/blog-dev.log
  
