#生产环境
spring:
  #    配置数据库连接
  datasource:
    username: zhenghao
    password: 123456
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    driver-class-name: com.mysql.jdbc.Driver
  #    设置自动建表与显示SQL语句
  jpa:
    hibernate:
      ddl-auto: update #默认
    show-sql: true
#    设置日志级别
logging:
  level:
    root: warn
    cn.zh.blog: info
  file: log/blog-pro.log
#指定服务访问端口
server:
  port: 8089